services:
    microservice:
        build:
            context: ./microservice
        image: microservice
        restart: unless-stopped
        expose:
            - "5000"
        deploy:
            replicas: 3


    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - microservice
        ports:
            - "5000:4000"


    nginx-html:
        image: nginx
        container_name: nginx-html
        restart: unless-stopped
        volumes:
            - ./html:/usr/share/nginx/html:ro
        depends_on:
            - nginx
        ports:
            - "8080:80"


